# Generated by Django 3.2.6 on 2021-12-14 00:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('numTeams', models.IntegerField(default=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('firstName', models.CharField(max_length=80)),
                ('lastName', models.CharField(max_length=80)),
                ('jerseyNumber', models.IntegerField(default=0)),
                ('position', models.CharField(max_length=80)),
                ('captain', models.BooleanField(default=False)),
                ('altCaptain', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rink',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('streetAddress', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('zip', models.CharField(max_length=80)),
                ('phoneNumber', models.CharField(max_length=80)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('numGames', models.CharField(max_length=3)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.division')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('regWins', models.IntegerField(default=0)),
                ('regLoses', models.IntegerField(default=0)),
                ('otWins', models.IntegerField(default=0)),
                ('otLoses', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('gamesPlayed', models.IntegerField(default=0)),
                ('playoffEligible', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.team'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('dateTime', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('awayTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Away_Team', to='home.team')),
                ('homeTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Home_Team', to='home.team')),
                ('rink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.rink')),
            ],
        ),
    ]
