# Generated by Django 3.2.6 on 2022-01-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='seasonActive',
            new_name='seasonComplted',
        ),
    ]
