# Generated by Django 3.2.6 on 2022-01-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_seasonactive_season_seasoncomplted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='seasonComplted',
            new_name='seasonCompleted',
        ),
    ]
