# Generated by Django 3.2.6 on 2021-12-15 15:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_division_numteams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('phoneNumber', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scorekeeper',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('phoneNumber', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='referees',
            field=models.ManyToManyField(blank=True, null=True, to='home.Referee'),
        ),
        migrations.AddField(
            model_name='game',
            name='scorekeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.scorekeeper'),
        ),
    ]
