# Generated by Django 3.2.6 on 2021-12-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211215_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
