# Generated by Django 3.2.6 on 2021-12-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211220_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rink',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time',
        ),
        migrations.CreateModel(
            name='IceSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('rink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.rink')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='iceSlot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.iceslot'),
        ),
    ]
