# Generated by Django 3.2.6 on 2022-01-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gameresult_quickreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='game',
        ),
    ]
