# Generated by Django 3.2.6 on 2022-01-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_penalty_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='assistSecondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Secondary_Assist', to='home.player'),
        ),
    ]
