# Generated by Django 3.2.6 on 2021-12-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_iceslot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='iceslot',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
