# Generated by Django 3.2.6 on 2022-01-28 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_scorekeeper_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorekeeper',
            name='user',
            field=models.OneToOneField(limit_choices_to={'type': 'SCOREKEEPER'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
