# Generated by Django 3.2.6 on 2021-12-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_iceslot_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='iceSlot',
            field=models.ForeignKey(blank=True, limit_choices_to={'available': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.iceslot'),
        ),
    ]
