# Generated by Django 3.2.6 on 2021-12-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_game_iceslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='seasons',
            field=models.ManyToManyField(blank=True, null=True, to='home.Season'),
        ),
    ]
