# Generated by Django 3.2.6 on 2021-12-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_division_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='currentSeason',
            field=models.BooleanField(default=True),
        ),
    ]
