# Generated by Django 3.2.6 on 2021-12-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_season_currentseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='seasons',
            field=models.ManyToManyField(blank=True, null=True, to='home.Season'),
        ),
        migrations.AddField(
            model_name='team',
            name='seasons',
            field=models.ManyToManyField(blank=True, null=True, to='home.Season'),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='seasons',
            field=models.ManyToManyField(blank=True, null=True, to='home.Season'),
        ),
    ]
