# Generated by Django 3.2.6 on 2021-12-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211221_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='currentSeason',
            field=models.BooleanField(default=False),
        ),
    ]
