# Generated by Django 3.2.6 on 2021-12-22 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_playerstats_seasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='seasons',
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='seasons',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.season'),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.season'),
        ),
    ]
