# Generated by Django 3.2.6 on 2021-12-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211221_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='seasons',
        ),
    ]
