# Generated by Django 3.2.6 on 2021-12-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_player_seasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='season',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='team',
        ),
    ]
