# Generated by Django 3.2.6 on 2021-12-23 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20211222_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.season'),
        ),
    ]
