# Generated by Django 3.2.6 on 2021-12-29 01:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('period', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('OT', 'OT')], max_length=100)),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Double Minor', 'Double Minor'), ('Major', 'Major'), ('Game Misconduct', 'Game Misconduct'), ('Match', 'Match')], max_length=100)),
                ('length', models.CharField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('10', '10')], max_length=100)),
                ('type', models.CharField(choices=[('Charging', 'Charging'), ('Cross-checking', 'Cross-checking'), ('Delay of game', 'Delay of game'), ('Elbowing', 'Elbowing'), ('Embellishment', 'Embellishment'), ('Goaltender interference', 'Goaltender interference'), ('High-sticking', 'High-sticking'), ('Hooking', 'Hooking'), ('Interference', 'Interference'), ('Roughing', 'Roughing'), ('Slashing', 'Slashing'), ('Tripping', 'Tripping'), ('Unsportsmanlike conduct', 'Unsportsmanlike conduct'), ('Too many men on the ice', 'Too many men on the ice'), ('Boarding', 'Boarding'), ('Fighting', 'Fighting')], max_length=100)),
                ('timeCommitted', models.CharField(max_length=80)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.playerstats')),
            ],
        ),
    ]
