# Generated by Django 3.2.6 on 2022-01-01 18:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211230_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempGameResults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('awayPlayers', models.ManyToManyField(blank=True, null=True, related_name='Away_Players_Temp', to='home.Player')),
                ('awayTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Away_Team_Temp', to='home.team')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.game')),
                ('homePlayers', models.ManyToManyField(blank=True, null=True, related_name='Home_Players_Temp', to='home.Player')),
                ('homeTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Home_Team_Temp', to='home.team')),
            ],
        ),
    ]
