# Generated by Django 3.2.6 on 2022-01-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_tempgameresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempgameresults',
            name='awayTeam',
        ),
        migrations.RemoveField(
            model_name='tempgameresults',
            name='homeTeam',
        ),
        migrations.AddField(
            model_name='tempgameresults',
            name='losingTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Losing_Team_Temp', to='home.team'),
        ),
        migrations.AddField(
            model_name='tempgameresults',
            name='tempGoals',
            field=models.ManyToManyField(blank=True, null=True, related_name='Goals_Temp', to='home.Goal'),
        ),
        migrations.AddField(
            model_name='tempgameresults',
            name='tempPenalties',
            field=models.ManyToManyField(blank=True, null=True, related_name='Penalties_Temp', to='home.Penalty'),
        ),
        migrations.AddField(
            model_name='tempgameresults',
            name='winningTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Winning_Team_Temp', to='home.team'),
        ),
        migrations.AlterField(
            model_name='tempgameresults',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.game', unique=True),
        ),
    ]
