# Generated by Django 3.2.6 on 2022-01-03 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20220102_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='seasons',
            field=models.ManyToManyField(blank=True, to='home.Season'),
        ),
        migrations.AlterField(
            model_name='game',
            name='referees',
            field=models.ManyToManyField(blank=True, to='home.Referee'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='assistPrimary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Primary_Assist', to='home.playerstats'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='assistSecondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Secondary_Assist', to='home.playerstats'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goalScorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Goal_Scorer', to='home.playerstats'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.playerstats'),
        ),
        migrations.AlterField(
            model_name='team',
            name='seasons',
            field=models.ManyToManyField(blank=True, to='home.Season'),
        ),
        migrations.AlterField(
            model_name='tempgameresults',
            name='awayPlayers',
            field=models.ManyToManyField(blank=True, related_name='Away_Players_Temp', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='tempgameresults',
            name='homePlayers',
            field=models.ManyToManyField(blank=True, related_name='Home_Players_Temp', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='tempgameresults',
            name='tempGoals',
            field=models.ManyToManyField(blank=True, related_name='Goals_Temp', to='home.Goal'),
        ),
        migrations.AlterField(
            model_name='tempgameresults',
            name='tempPenalties',
            field=models.ManyToManyField(blank=True, related_name='Penalties_Temp', to='home.Penalty'),
        ),
    ]
