# Generated by Django 3.2.6 on 2022-01-03 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_goal_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='game',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.game'),
            preserve_default=False,
        ),
    ]
