# Generated by Django 3.2.6 on 2022-01-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_tempgameresults_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempgameresults',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.game'),
        ),
    ]
